name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: '.node-version'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - name: Update Npm
        run: npm i npm@latest -g

      - name: Install Dependencies
        run: pnpm install

      - name: Build Code
        run: pnpm run build

      - name: Publish Package
        run: pnpm run publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Current Change Log
        run: pnpm run build:change-log:current

      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./CURRENT_CHANGELOG.md
          make_latest: true
          tag_name: ${{ github.ref_name }}
